### ISSUE TITLE
Via requests that have hint data for some but not all points return incorrect routes 

### ISSUE THREAD

**Issue by JesseCrocker** [mapzen/routing#9]
This looks like it was fixed in OSRM a year ago, see Project-OSRM/osrm-backend#914

**Comment by randymeech** [comment]
Thanks -- we're rolling out a new routing service this month:

https://mapzen.com/blog/valhalla-intro
https://mapzen.com/blog/valhalla-why_tiles

So we're not going to be updating OSRM, apologies. There will be an OSRM-compatibility mode in the new service. Stay tuned to Twitter and our blog for service updates if you're relying on this.
